#!/usr/bin/env node
/* Turn save files into gallery presets.
     node tools/json2preset.js out.js id1=path1.json[:subtitle] id2=path2.json ...
   Writes a script that pushes one preset per file onto PRESETS (include it in
   index.html after presets.js). Prefix an id with ^ to put that card FIRST
   in the gallery (^lalaland-v6=file.json). Chains are emitted as
   [libId, mirror, beats, { aim, gapBefore, chst, arms, note }] rows, so the
   result is exactly what loadPreset() builds from a hand-written preset. */
const fs = require('fs');
const [out, ...specs] = process.argv.slice(2);
if (!out || !specs.length) { console.error('usage: json2preset.js out.js id=file.json[:subtitle] ...'); process.exit(1); }
const presets = specs.map((spec) => {
  const [rawId, rest] = spec.split('=');
  const front = rawId.startsWith('^'), id = rawId.replace(/^\^/, '');
  const [file, subtitle] = rest.split(/:(.*)/s);
  const d = JSON.parse(fs.readFileSync(file, 'utf8')), p = d.program;
  const chain = p.elements.map((e) => {
    const o = {};
    if (e.aim) o.aim = +(+e.aim).toFixed(2);
    if (e.gapBefore) o.gapBefore = +(+e.gapBefore).toFixed(3);
    if (e.chst) o.chst = true;
    if (e.arms) o.arms = e.arms;
    if (e.note) o.note = e.note;
    return [e.libId, !!e.mirror, e.beats, o];
  });
  return { front, id, name: p.name, subtitle: subtitle || (p.notes || '').slice(0, 140), credit: p.credit || 'Original choreography',
    level: p.level, bpm: p.bpm, speedScale: p.speedScale, start: p.start,
    music: p.musicName || p.musicDuration ? { name: p.musicName || 'lalala.mp3', duration: p.musicDuration, offset: p.offset || 0 } : undefined,
    notes: p.notes || '', highlights: p.highlights || [], chain };
});
fs.writeFileSync(out, '/* generated by tools/json2preset.js — do not edit by hand */\n' +
  presets.map((pr) => { const { front, ...rest } = pr; return `PRESETS.${front ? 'unshift' : 'push'}(${JSON.stringify(rest, null, 1)});`; }).join('\n') + '\n');
console.log(`wrote ${presets.length} preset(s) to ${out}`);
