#!/bin/sh
# Build js/local.js — your own programs and remix deck, loaded by index.html
# after the shipped presets. Everything under private/ is gitignored, so this
# is how a skater's programs stay on their machine while the repo stays
# shareable. Run it after editing anything in private/.
#
#   private/presets-personal.js      PRESETS.push(...) entries (hand-written or from json2preset)
#   private/variants.js              a remix deck (SECTIONS / VARIANTS / REMIX_PROGRAMS), optional
#   private/programs/*.json          save files; published as gallery cards via json2preset
cd "$(dirname "$0")/.." || exit 1
mkdir -p private
out=js/local.js
{
  echo "/* generated by tools/publish-local.sh from private/ — gitignored, do not edit by hand */"
  [ -f private/presets-personal.js ] && cat private/presets-personal.js
  if ls private/programs/*.json >/dev/null 2>&1; then
    # the program named in private/FRONT (an id) goes to the front of the gallery
    front=$(cat private/FRONT 2>/dev/null)
    args=""
    for f in private/programs/*.json; do
      id=$(basename "$f" .json)
      if [ "$id" = "$front" ]; then args="$args ^$id=$f"; else args="$args $id=$f"; fi
    done
    node tools/json2preset.js /tmp/_local_programs.js $args >&2
    cat /tmp/_local_programs.js; rm -f /tmp/_local_programs.js
  fi
  [ -f private/variants.js ] && cat private/variants.js
} > "$out"
echo "wrote $out ($(wc -l < "$out") lines)"
